Update workflows

diff --git a/.github/workflows/gradle-publish-snapshot.yml b/.github/workflows/gradle-publish-snapshot.yml
--- a/.github/workflows/gradle-publish-snapshot.yml
+++ b/.github/workflows/gradle-publish-snapshot.yml
@@ -4,26 +4,29 @@ on:
   workflow_dispatch:
   schedule:
     - cron: "0 15 * * 5"  # friday 15:00 UTC
+
 jobs:
   check-branch:
+    name: Check Branch
     runs-on: ubuntu-latest
     steps:
       - name: Check Branch
-        if: github.ref != 'refs/heads/main'
+        if: startsWith(github.ref, 'refs/heads/')
         run: |
-          echo "::error title=wrong branch selected::this workflow must be run on the 'main' branch"
-          exit 1
+          BRANCH="${GITHUB_REF#refs/heads/}"
+          if [[ "$BRANCH" != "main" && "$BRANCH" != "dev" && "$BRANCH" != dev/* && "$BRANCH" != release/* ]]; then
+            echo "::error title=wrong branch selected::this workflow must be run on 'main', 'dev/*' or 'release/*' branches"
+            exit 1
+          fi
 
   check-updates:
+    name: Check Updates
     runs-on: ubuntu-latest
     outputs:
       should_run: ${{ steps.check.outputs.should_run }}
     steps:
       - name: Checkout
         uses: actions/checkout@v5
-        with:
-          ref: main
-          fetch-depth: 50
 
       - name: Check if SNAPSHOT publish is applicable
         id: check
@@ -42,14 +45,13 @@ jobs:
           fi
 
   publish-snapshot:
+    name: Publish problem4j-core SNAPSHOT
     needs: [check-branch, check-updates]
     if: needs.check-updates.outputs.should_run == 'true'
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v5
-        with:
-          ref: main
 
       - name: Set up JDK 17
         uses: actions/setup-java@v5
@@ -80,7 +82,7 @@ jobs:
           echo "::notice::evaluated snapshot version: $SNAPSHOT_VERSION"
           echo "version=$SNAPSHOT_VERSION" >> $GITHUB_OUTPUT
 
-      - name: Publish Snapshot with Gradle Wrapper
+      - name: Publish Snapshot
         env:
           SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
           SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
